const PRODUCT_FETCH = "PRODUCT_FETCH";
const PRODUCT_ADD = "PRODUCT_ADD";

const CARD_ADD = "PRODUCT_ADD";
const CARD_REMOVE = "PRODUCT_REMOVE";
const CARD_SORT = "PRODUCT_ADD";

export { PRODUCT_ADD, PRODUCT_FETCH, CARD_ADD, CARD_REMOVE, CARD_SORT };
