const PRODUCT_FETCH = "PRODUCT_FETCH";
const PRODUCT_ADD = "PRODUCT_ADD";

const CARD_ADD = "CARD_ADD";
const CARD_REMOVE = "CARD_REMOVE";
const CARD_SORT = "CARD_SORT";

export { PRODUCT_ADD, PRODUCT_FETCH, CARD_ADD, CARD_REMOVE, CARD_SORT };
